Repository noncelab/coconut_vault, pull requests merged in 2025-04, with the labels that each got.

#101 [14-1016] Feat/batch tx
  CHANGELOG.md
  assets/i18n/kr.i18n.yaml
  ios/Runner.xcodeproj/project.pbxproj
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/main.dart
  lib/managers/isolate_manager.dart
  lib/model/common/wallet_address.dart
  lib/model/multisig/multisig_vault_list_item.dart
  lib/model/single_sig/single_sig_vault_list_item.dart
  lib/oss_licenses.dart
  lib/providers/auth_provider.dart
  lib/providers/sign_provider.dart
  lib/providers/view_model/address_list_view_model.dart
  lib/providers/view_model/airgap/multisig_sign_view_model.dart
  lib/providers/view_model/airgap/psbt_confirmation_view_model.dart
  lib/providers/view_model/airgap/single_sig_sign_view_model.dart
  lib/providers/view_model/multisig_signer_bsms_export_view_model.dart
  lib/providers/view_model/signer_assignment_view_model.dart
  lib/providers/wallet_provider.dart
  lib/screens/airgap/multisig_sign_screen.dart
  lib/screens/airgap/psbt_confirmation_screen.dart
  lib/screens/airgap/single_sig_sign_screen.dart
  lib/screens/common/multisig_bsms_scanner_screen.dart
  lib/screens/vault_creation/multisig/import_confirmation_screen.dart
  lib/screens/vault_creation/multisig/signer_assignment_screen.dart
  lib/screens/vault_menu/info/multisig_setup_info_screen.dart
  lib/screens/vault_menu/info/multisig_setup_screen.dart
  lib/screens/vault_menu/info/single_sig_setup_info_screen.dart
  lib/utils/isolate_handler.dart
  lib/widgets/card/information_item_card.dart
  lib/widgets/information_item_row.dart
  lib/widgets/multisig/card/signer_bsms_info_card.dart
  pubspec.yaml
Labels: 💫 feat

#116 [111] 복원 플로우 화면 구현
  assets/i18n/kr.i18n.yaml
  lib/app.dart
  lib/constants/app_routes.dart
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/providers/view_model/vault_list_restoration_view_model.dart
  lib/screens/app_update_helpers/restoration_info_screen.dart
  lib/screens/app_update_helpers/vault_list_restoration_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/widgets/indicator/percent_progress_indicator.dart
Labels: 🎨 UI

#114 Feat/advanced mode: 니모닉 사용 여부 선택
  assets/i18n/kr.i18n.yaml
  lib/constants/shared_preferences_keys.dart
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/providers/visibility_provider.dart
  lib/screens/settings/settings_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_coinflip_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_generation_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_import_screen.dart
Labels: 💫 feat

#115 [107] 업데이트 준비 과정에서 필요한 복원 파일 생성 및 복원 기능
  android/app/build.gradle
  integration_test/README.md
  integration_test/integration_test_utils.dart
  integration_test/secure_key_generator_test.dart
  integration_test/update_preparation_test.dart
  lib/constants/secure_storage_keys.dart
  lib/managers/wallet_list_manager.dart
  lib/model/multisig/multisig_vault_list_item.dart
  lib/model/multisig/multisig_vault_list_item.g.dart
  lib/model/single_sig/single_sig_vault_list_item.dart
  lib/model/single_sig/single_sig_vault_list_item.g.dart
  lib/providers/connectivity_provider.dart
  lib/providers/view_model/vault_menu/vault_setup_info_view_model_base.dart
  lib/providers/wallet_provider.dart
  lib/screens/common/multisig_bsms_scanner_screen.dart
  lib/screens/vault_creation/vault_name_and_icon_setup_screen.dart
  lib/screens/vault_menu/info/multisig_setup_screen.dart
  lib/utils/aes_crypto.dart
  lib/utils/coconut/update_preparation.dart
  lib/utils/file_storage.dart
  lib/utils/isolate_handler.dart
  lib/utils/secure_key_generator.dart
  macos/Runner/AppDelegate.swift
  pubspec.yaml
  test/utils/aes_crypto_test.dart
  test/utils/secure_key_generator_test.dart
Labels: 💫 feat

#113 [105] 업데이트 준비 플로우 화면
  assets/i18n/kr.i18n.yaml
  assets/svg/text-field-clear.svg
  lib/app.dart
  lib/constants/app_routes.dart
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/providers/view_model/app_update_preparation_view_model.dart
  lib/providers/view_model/vault_list_restoration_view_model.dart
  lib/screens/app_update_helpers/app_update_preparation_screen.dart
  lib/screens/app_update_helpers/restoration_info_screen.dart
  lib/screens/app_update_helpers/vault_list_restoration_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/widgets/button/fixed_bottom_button.dart
  lib/widgets/custom_loading_overlay.dart
  lib/widgets/indicator/countdown_spinner.dart
  lib/widgets/indicator/gradient_progress_indicator.dart
  lib/widgets/indicator/percent_progress_indicator.dart
  pubspec.yaml
Labels: 💫 feat, 🎨 UI

#118 [106] 니모닉 확인 기능
  integration_test/README.md
  integration_test/integration_test_utils.dart
  integration_test/update_preparation_test.dart
  lib/constants/shared_preferences_keys.dart
  lib/localization/strings.g.dart
  lib/localization/strings_kr.g.dart
  lib/providers/view_model/app_update_preparation_view_model.dart
  lib/providers/wallet_provider.dart
  lib/screens/app_update_helpers/app_update_preparation_screen.dart
  lib/screens/settings/settings_screen.dart
Labels: 💫 feat

#119 [108] 복원 파일 생성 & 지갑 복원
  integration_test/README.md
  integration_test/update_preparation_test.dart
  lib/app.dart
  lib/enums/app_update_step_enum.dart
  lib/main.dart
  lib/providers/view_model/app_update_preparation_view_model.dart
  lib/providers/view_model/vault_list_restoration_view_model.dart
  lib/screens/app_update_helpers/app_update_preparation_screen.dart
  lib/screens/app_update_helpers/vault_list_restoration_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/utils/coconut/update_preparation.dart
  lib/utils/isolate_handler2.dart
  lib/widgets/button/fixed_bottom_button.dart
Labels: 💫 feat, 🎨 UI

#123 [109] 앱 진입 시 화면 이동
  CHANGELOG.md
  lib/app.dart
  lib/constants/shared_preferences_keys.dart
  lib/enums/pin_check_context_enum.dart
  lib/managers/wallet_list_manager.dart
  lib/providers/auth_provider.dart
  lib/providers/view_model/app_update_preparation_view_model.dart
  lib/providers/view_model/start_view_model.dart
  lib/screens/app_update/restoration_info_screen.dart
  lib/screens/app_update/vault_list_restoration_screen.dart
  lib/screens/common/pin_check_screen.dart
  lib/screens/common/start_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/utils/app_version_util.dart
  lib/utils/coconut/update_preparation.dart
Labels: 💫 feat

#130 [128] 니모닉 확인 TextField 커서 이동 시 입력 오류
  lib/screens/app_update/app_update_preparation_screen.dart
  pubspec.yaml
Labels: 🐛 bug

#137 [203] 복사하기 버튼 변경
  assets/i18n/kr.i18n.yaml
  assets/svg/copy.svg
  lib/screens/vault_menu/info/mnemonic_view_screen.dart
  lib/screens/vault_menu/info/multisig_bsms_screen.dart
  lib/screens/vault_menu/sync_to_wallet/export_detail_screen.dart
  lib/styles.dart
  lib/utils/toast.dart
  lib/widgets/button/clipboard_button.dart
  lib/widgets/button/copy_text_container.dart
  lib/widgets/qrcode_info.dart
  lib/widgets/qrcode_link_info.dart
  pubspec.yaml
Labels: 🎨 UI
