Repository noncelab/coconut_vault, pull requests merged in 2025-08, with the labels that each got.

#184 [183] 볼트 CDS 적용
  lib/screens/airgap/multisig_sign_screen.dart
  lib/screens/airgap/multisig_signer_qr_bottom_sheet.dart
  lib/screens/airgap/psbt_confirmation_screen.dart
  lib/screens/airgap/psbt_scanner_screen.dart
  lib/screens/airgap/signed_transaction_qr_screen.dart
  lib/screens/common/multisig_bsms_scanner_screen.dart
  lib/screens/home/tutorial_screen.dart
  lib/screens/home/vault_list_screen.dart
  lib/screens/start_guide/welcome_screen.dart
  lib/screens/vault_creation/multisig/import_confirmation_screen.dart
  lib/screens/vault_creation/multisig/signer_assignment_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_coinflip_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_generation_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_import_screen.dart
  lib/screens/vault_menu/multisig_signer_bsms_export_screen.dart
  lib/screens/vault_menu/sync_to_wallet/sync_to_wallet_screen.dart
  lib/widgets/appbar/frosted_appbar.dart
  lib/widgets/button/fixed_bottom_button.dart
  lib/widgets/button/small_action_button.dart
  lib/widgets/custom_dialog.dart
  lib/widgets/textfield/custom_textfield.dart
  lib/widgets/vault_name_icon_edit_palette.dart
  pubspec.yaml
Labels: ♻️ refactor

#174 [173] 앱이 Android 15(API 수준 35) 이상을 타겟팅해야 함
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  lib/packages/qr-code-scanner/CHANGELOG.md
  lib/packages/qr-code-scanner/LICENSE
  lib/packages/qr-code-scanner/README.md
  lib/packages/qr-code-scanner/analysis_options.yaml
  lib/packages/qr-code-scanner/android/build.gradle
  lib/packages/qr-code-scanner/android/gradle.properties
  lib/packages/qr-code-scanner/android/settings.gradle
  lib/packages/qr-code-scanner/android/src/main/AndroidManifest.xml
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/CustomFramingRectBarcodeView.kt
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QrActivityLifecycleCallbacks.kt
  lib/packages/qr-code-scanner/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QrShared.kt
  lib/packages/qr-code-scanner/ios/Classes/FlutterQrPlugin.h
  lib/packages/qr-code-scanner/ios/Classes/FlutterQrPlugin.m
  lib/packages/qr-code-scanner/ios/Classes/QRView.swift
  lib/packages/qr-code-scanner/ios/Classes/QRViewFactory.swift
  lib/packages/qr-code-scanner/ios/Classes/SwiftFlutterQrPlugin.swift
  lib/packages/qr-code-scanner/ios/qr_code_scanner.podspec
  lib/packages/qr-code-scanner/lib/qr_code_scanner.dart
  lib/packages/qr-code-scanner/lib/src/lifecycle_event_handler.dart
  lib/packages/qr-code-scanner/lib/src/qr_code_scanner.dart
  lib/packages/qr-code-scanner/lib/src/qr_scanner_overlay_shape.dart
  lib/packages/qr-code-scanner/lib/src/types/barcode.dart
  lib/packages/qr-code-scanner/lib/src/types/barcode_format.dart
  lib/packages/qr-code-scanner/lib/src/types/camera.dart
  lib/packages/qr-code-scanner/lib/src/types/camera_exception.dart
  lib/packages/qr-code-scanner/lib/src/types/features.dart
  lib/packages/qr-code-scanner/lib/src/web/flutter_qr_stub.dart
  lib/packages/qr-code-scanner/lib/src/web/flutter_qr_web.dart
  lib/packages/qr-code-scanner/lib/src/web/jsqr.dart
  lib/packages/qr-code-scanner/lib/src/web/media.dart
  lib/packages/qr-code-scanner/pubspec.yaml
  pubspec.yaml
Labels: 💫 feat

#186 [180] 니모닉 생성 및 확인 UI 변경
  assets/i18n/en.i18n.yaml
  assets/i18n/kr.i18n.yaml
  lib/app.dart
  lib/constants/app_routes.dart
  lib/screens/common/pin_check_screen.dart
  lib/screens/settings/pin_setting_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_coinflip_confirmation_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_coinflip_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_confirmation_bottom_sheet.dart
  lib/screens/vault_creation/single_sig/mnemonic_confirmation_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_generation_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_import_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_verify_screen.dart
  lib/screens/vault_creation/single_sig/security_self_check_screen.dart
  lib/screens/vault_creation/vault_creation_options_screen.dart
  lib/screens/vault_creation/vault_name_and_icon_setup_screen.dart
  lib/screens/vault_creation/vault_type_selection_screen.dart
  lib/screens/vault_menu/info/mnemonic_view_screen.dart
  lib/screens/vault_menu/info/passphrase_verification_screen.dart
  lib/screens/vault_menu/info/single_sig_setup_info_screen.dart
  lib/utils/vibration_util.dart
  lib/widgets/button/fixed_bottom_button.dart
  lib/widgets/button/fixed_bottom_tween_button.dart
  lib/widgets/button/shrink_animation_button.dart
  lib/widgets/vault_name_icon_edit_palette.dart
  pubspec.yaml
Labels: 💫 feat, 🎨 UI
