Repository noncelab/coconut_vault, pull requests merged in 2025-05, with the labels that each got.

#135 [133] Bug - 핀 체크 화면에 진입 후 잠시 입력 불가 상태
  integration_test/README.md
  integration_test/app_lock_test.dart
  lib/constants/pin_constants.dart
  lib/enums/pin_check_context_enum.dart
  lib/providers/auth_provider.dart
  lib/screens/airgap/multisig_sign_screen.dart
  lib/screens/airgap/single_sig_sign_screen.dart
  lib/screens/app_update/restoration_info_screen.dart
  lib/screens/common/pin_check_screen.dart
  lib/screens/common/pin_input_screen.dart
  lib/screens/common/start_screen.dart
  lib/screens/settings/pin_setting_screen.dart
  lib/screens/settings/settings_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_import_screen.dart
  lib/screens/vault_menu/info/multisig_setup_info_screen.dart
  lib/screens/vault_menu/info/single_sig_setup_info_screen.dart
  lib/widgets/card/information_item_card.dart
  lib/widgets/textfield/custom_textfield.dart
Labels: 🐛 bug

#134 chore(debug-mode): debug 모드에서 스크린샷 허용
  ios/Podfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  lib/main.dart
Labels: ⚙️ chore

#138 [UI] 볼트 홈 화면 수정
  assets/i18n/kr.i18n.yaml
  assets/svg/book.svg
  assets/svg/kebab.svg
  assets/svg/wallet-plus.svg
  lib/managers/isolate_manager.dart
  lib/managers/wallet_list_manager.dart
  lib/providers/wallet_provider.dart
  lib/screens/home/vault_list_screen.dart
  lib/screens/vault_creation/multisig/signer_assignment_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_coinflip_screen.dart
  lib/screens/vault_creation/single_sig/mnemonic_confirmation_bottom_sheet.dart
  lib/screens/vault_menu/info/multisig_setup_info_screen.dart
  lib/screens/vault_menu/info/single_sig_setup_info_screen.dart
  lib/utils/dashed_border_painter.dart
  lib/widgets/appbar/frosted_appbar.dart
  lib/widgets/button/shrink_animation_button.dart
  lib/widgets/card/vault_addition_guide_card.dart
  lib/widgets/vault_row_item.dart
  pubspec.yaml
Labels: ♻️ refactor, 🎨 UI
