Repository noncelab/coconut_vault, pull requests merged in 2025-02, with the labels that each got.

#83 Fix/loss vault list
  ios/Runner.xcodeproj/project.pbxproj
  lib/app.dart
  lib/main.dart
  lib/main_route_guard.dart
  lib/model/manager/wallet_list_manager.dart
  lib/model/state/vault_model.dart
  lib/screens/home/vault_list_screen.dart
  lib/screens/pin_check_screen.dart
  lib/screens/start_screen.dart
  lib/screens/vault_creation/vault_name_icon_setup_screen.dart
  lib/utils/logger.dart
Labels: 🐛 bug

#88 Refactor/vm start screen
  lib/app.dart
  lib/providers/connectivity_provider.dart
  lib/providers/view_model/start_view_model.dart
  lib/screens/home/vault_list_screen.dart
  lib/screens/start_guide/guide_screen.dart
  lib/screens/start_guide/welcome_screen.dart
  lib/screens/start_screen.dart
  lib/screens/tutorial_screen.dart
  lib/utils/router_util.dart
Labels: ♻️ refactor

#90 fix(biometrics): 생체 인증 요청 로직 수정
  lib/providers/auth_provider.dart
  lib/screens/common/pin_check_screen.dart
  lib/screens/setting/settings_screen.dart
Labels: 🐛 bug

#95 [13-989] 메뉴 하위 페이지2
  lib/providers/view_model/address_list_view_model.dart
  lib/providers/view_model/multisig_signer_bsms_export_view_model.dart
  lib/screens/vault_menu/address_list_screen.dart
  lib/screens/vault_menu/multisig_signer_bsms_export_screen.dart
  lib/screens/vault_menu/sync_to_wallet/export_detail_screen.dart
  lib/screens/vault_menu/sync_to_wallet/sync_to_wallet_screen.dart
  lib/widgets/card/address_card.dart
Labels: ♻️ refactor

#97 [13-1004] signer_assignment 화면에서 자동으로 리스트가 펼쳐지지 않는 버그 해결
  lib/providers/view_model/signer_assignment_view_model.dart
  lib/screens/vault_creation/multisig/signer_assignment_screen.dart
Labels: 🐛 bug, 🎨 UI
